### ISSUE TITLE
Portability issue regarding SWAP64(x) impementation

### ISSUE THREAD

**Issue by kaback** [slomkowski/mumlib#12]
Your implementation of SWAP64(x) seems not to be portable.

I am using a raspberry pi and got compiler errors. I have no idea how to implement this in a portable way.

For my needs i changed it into some raspberry pi specific and also not portable version:
# define bswap_64(x) \

({ \
        uint64_t __x = (x); \
        ((uint64_t)( \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x00000000000000ffULL) << 56) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x000000000000ff00ULL) << 40) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x0000000000ff0000ULL) << 24) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x00000000ff000000ULL) <<  8) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x000000ff00000000ULL) >>  8) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x0000ff0000000000ULL) >> 24) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0x00ff000000000000ULL) >> 40) | \
                (uint64_t)(((uint64_t)(__x) & (uint64_t)0xff00000000000000ULL) >> 56) )); \
})
# define SWAP64(x) bswap_64(x)

**Comment by slomkowski** [comment]
@Hunter522 fixed it in his fork: https://github.com/Hunter522/mumlib/commit/66672807d5064bf20fb63ec49ab584f2240a3ced

**Comment by Hunter522** [comment]
Had similar issues on my pi, I submitted a pull request #13

**Comment by slomkowski** [comment]
@kaback I merged the pull request.
