### ISSUE TITLE
receiving a message with a html image throws.

### ISSUE THREAD

**Issue by ysblokje** [slomkowski/mumlib#7]
Receiving a  message with : 
`<img src="data:image/jpeg;base64 %2F9j%2F4AAQSkZJRgABAQEASABIAAD%2F4QAWRXh etcetcetc />` 

Throws with some nice integer numbers . 
(i've turned the throw to a logger.warn) 

1453155950 WARN mumlib.Mumlib : unknown message type: 18536
1453155950 WARN mumlib.Mumlib : unknown message type: 14414
1453155950 WARN mumlib.Mumlib : unknown message type: 21602

**Comment by slomkowski** [comment]
I increased input buffer to 128kB to handle images. Can you try the current version?

In my case _unknown message type_ has never occurred. In case the fix doesn't work, please provide your Mumble & Murmur versions etc.

**Comment by slomkowski** [comment]
@ysblokje did my fix help? Can you confirm it's solved?

**Comment by ysblokje** [comment]
@slomkowski  Sorry I forgot to reply but yes it did ! Also you might take a look at my current code. I found a semi bug and added a new method (and restored the old one regarding audio)

**Comment by ysblokje** [comment]
I'm closing the bug. Haven't had any new problems since your patch.
