### ISSUE TITLE
Make Error on Mac

### ISSUE THREAD

**Issue by h27han** [slomkowski/mumlib#9]
I cloned the repository, install all dependencies through homebrew on mac, and run the cmake. It tells me that openssl include directory is not found, so I added the -D, and cmake runs successfully.
![image](https://cloud.githubusercontent.com/assets/10564698/12517458/c78bd8da-c100-11e5-90c4-c29216c6eb28.png)
However after that, I tried to run the MakeFile, but it pops up 
![image](https://cloud.githubusercontent.com/assets/10564698/12517482/e476912e-c100-11e5-9d97-a32fb292fb94.png)
![image](https://cloud.githubusercontent.com/assets/10564698/12517492/eff4c7aa-c100-11e5-9146-83cccb6051ac.png)
which seem to be error with the boost library.
Any clue what happened or where I can download the right boost library?
Thanks

**Comment by slomkowski** [comment]
I'm not familiar with Macs, but I found that `getipnodebyaddr()` is system-specific API function. Perhaps there are some system headers missing?

**Comment by slomkowski** [comment]
Did you solve this problem?

**Comment by HeroCC** [comment]
I know it is a while later, but I'm still having this issue. Trying to compile on a Mac and I get almost the exact same errors (minus the getIpNodeByAddr()). Here is my log file: 

[makeLog2.txt](https://github.com/slomkowski/mumlib/files/2138622/makeLog2.txt)

**Comment by HeroCC** [comment]
I was able to find a fix for this and commited it here

**Comment by HeroCC** [comment]
I was able to find a fix for this and put it in my fork here: https://github.com/HeroCC/mumlib/commit/028e5a2697a5c8438352a51b331f36b01a1b06ac. I was only able to test it on my system, so anyone who can test it on other systems please let me know if it works!
